// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TrilhaBee.Repositorio.Migrations
{
    [DbContext(typeof(TrilhaBeeContexto))]
    partial class TrilhaBeeContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.AcaoManejo", b =>
                {
                    b.Property<int>("AcaoManejoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AcaoManejoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AcaoManejoID"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataRealizacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descricao");

                    b.Property<int>("InspecaoID")
                        .HasColumnType("int");

                    b.Property<string>("TipoManejo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TipoManejo");

                    b.HasKey("AcaoManejoID");

                    b.HasIndex("InspecaoID");

                    b.ToTable("AcaoManejo", (string)null);
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.AlertaIA", b =>
                {
                    b.Property<int>("AlertaIAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AlertaIAID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlertaIAID"));

                    b.Property<int>("ColmeiaID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataGeracao");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Mensagem");

                    b.Property<string>("NivelGravidade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NivelGravidade");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("bit")
                        .HasColumnName("Resolvido");

                    b.HasKey("AlertaIAID");

                    b.HasIndex("ColmeiaID");

                    b.ToTable("AlertaIA", (string)null);
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Apiario", b =>
                {
                    b.Property<int>("ApiarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ApiarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApiarioID"));

                    b.Property<int>("Capacidade")
                        .HasColumnType("int")
                        .HasColumnName("Capacidade");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataCriacao");

                    b.Property<string>("Localizacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)")
                        .HasColumnName("Localizacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("Nome");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ApiarioID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Apiario", (string)null);
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Colmeia", b =>
                {
                    b.Property<int>("ColmeiaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ColmeiaID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ColmeiaID"));

                    b.Property<int>("ApiarioID")
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit")
                        .HasColumnName("Ativa");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInstalacao");

                    b.Property<string>("Identificacao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Identificacao");

                    b.Property<string>("TipoAbelha")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TipoAbelha");

                    b.HasKey("ColmeiaID");

                    b.HasIndex("ApiarioID");

                    b.ToTable("Colmeia", (string)null);
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Inspecao", b =>
                {
                    b.Property<int>("InspecaoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("InspecaoID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InspecaoID"));

                    b.Property<string>("Clima")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColmeiaID")
                        .HasColumnType("int");

                    b.Property<string>("CondicaoGeral")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CondicaoGeral");

                    b.Property<DateTime>("DataInspecao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DataInspecao");

                    b.Property<int>("ForcaColmeia")
                        .HasColumnType("int");

                    b.Property<int>("NivelAlimento")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Observacoes");

                    b.Property<bool>("TemPostura")
                        .HasColumnType("bit");

                    b.Property<bool>("TemRainha")
                        .HasColumnType("bit")
                        .HasColumnName("TemRainha");

                    b.Property<string>("Temperamento")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InspecaoID");

                    b.HasIndex("ColmeiaID");

                    b.ToTable("Inspecao", (string)null);
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UsuarioID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Senha");

                    b.Property<int>("Tipo")
                        .HasColumnType("int")
                        .HasColumnName("Tipo");

                    b.HasKey("UsuarioID");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.AcaoManejo", b =>
                {
                    b.HasOne("TrilhaBee.Dominio.Entidades.Inspecao", "Inspecao")
                        .WithMany("AcoesManejo")
                        .HasForeignKey("InspecaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inspecao");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.AlertaIA", b =>
                {
                    b.HasOne("TrilhaBee.Dominio.Entidades.Colmeia", "Colmeia")
                        .WithMany("Alertas")
                        .HasForeignKey("ColmeiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmeia");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Apiario", b =>
                {
                    b.HasOne("TrilhaBee.Dominio.Entidades.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Colmeia", b =>
                {
                    b.HasOne("TrilhaBee.Dominio.Entidades.Apiario", "Apiario")
                        .WithMany("Colmeias")
                        .HasForeignKey("ApiarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apiario");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Inspecao", b =>
                {
                    b.HasOne("TrilhaBee.Dominio.Entidades.Colmeia", "Colmeia")
                        .WithMany("Inspecoes")
                        .HasForeignKey("ColmeiaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colmeia");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Apiario", b =>
                {
                    b.Navigation("Colmeias");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Colmeia", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Inspecoes");
                });

            modelBuilder.Entity("TrilhaBee.Dominio.Entidades.Inspecao", b =>
                {
                    b.Navigation("AcoesManejo");
                });
#pragma warning restore 612, 618
        }
    }
}
